### PR TITLE
Fix Logic Error in MegaRAID Checks

### LINKED ISSUE #13: megacli and LD lists
I am not a user of sensu nor do I directly utilize any plugins within this repo, however I have noticed what looks to be a bug with how you are checking the logical devices on Megaraid/LSI controllers.

Specifically, within https://github.com/sensu-plugins/sensu-plugins-raid-checks/blob/master/bin/check-megaraid-sas-status.rb -- it looks as though You first run the following:

```
$ /opt/MegaRAID/MegaCli/MegaCli64 -LDGetNum -a0
```

This returns a status code which equates to the number of logical devices there are. You then loop through the devices by index of zero, to the number of logical devices minus one: https://github.com/sensu-plugins/sensu-plugins-raid-checks/blob/master/bin/check-megaraid-sas-status.rb#L56. The problem with this is that megaraid cards do not always begin with index zero (e.g. spanning across multiple controllers, and/or if a LD is removed after a box has been kicked). Thus, the way that this loops through them is flawed.

For example, [here](http://dropb.in/t/gepfir) is a pastebin of some example output from a megaraid controller, showing output for `-LDGetNum` and `-LDInfo` for the array. As you can see, using index 0 won't always work.

I may suggest using `-LDInfo -LALL` and using regex to parse out `Virtual Drive: <number>` or a similar approach, which is a bit more flexible (as this type of output doesn't seem to change between versions).

Only a suggestion, though.

### PR DESCRIPTION
**Pull request by SeanSith**
Fixes #13. Parses output to retrieve list of virtual drives, checks drives for errors.

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [X] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [X] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
Thanks for your contribution to Sensu plugins! Without people like you submitting PRs we couldn't run the project. I will review it shortly.

File: bin/check-megaraid-sas-status.rb [hunk 1]
```diff
@@ -53,12 +53,18 @@ class CheckMegaRAID < Sensu::Plugin::Check::CLI
...
+    stdout.each do |line|
+      if line =~ /^Virtual Drive:/
+        virtual_drives << line.gsub(/^Virtual Drive: (\d+) .*$/, '\1')
+      end
+    end
+    virtual_drives.each do |i|
       # and check them in turn
       stdout = `#{config[:megaraidcmd]} -LDInfo -L#{i} -a#{config[:controller]} `
-      unless Regexp.new('State\s*:\s*Optimal').match?(stdout)
+      unless Regexp.new(/State\s+:\s+Optimal/).match(stdout)
```
Comment (majormoses) [inline bin/check-megaraid-sas-status.rb:67]: the `.match?` while is indeed faster and more resource conscious as it discards the actual matchdata and only returns a boolean value it did not exist prior to ruby `2.4`. I will add a comment to change that back when we drop ruby `< 2.4` support (which we won't do until after ruby 2.4 is EOL).

**Review by majormoses — APPROVED** [review]
LGTM
